In [2]:
#OR GATE 
import tensorflow as tf
import numpy as np
x=tf.placeholder(tf.float32,shape=[None,2])
y=tf.placeholder(tf.float32,shape=[None,1])

weights=tf.Variable(tf.random_normal([2,1]),dtype=tf.float32)
bias=tf.Variable(tf.random_normal([1]),dtype=tf.float32)



multiply1=tf.add(tf.matmul(x,weights),bias)
z=tf.nn.sigmoid(multiply1)


cost=tf.reduce_mean((y*tf.log(z)+(1-y)*tf.log(1-z))*-1)
optimizer = tf.train.GradientDescentOptimizer(0.01).minimize(cost)

inp=np.array([[0,0],[0,1],[1,0],[1,1]])
op=np.array([[0],[1],[1],[1]])
with tf.Session() as sess:
   
    tf.global_variables_initializer().run()
    for i in range(12001):
        res,_=sess.run([cost,optimizer],feed_dict={x:inp,y:op})
        if i%1000==0:
            print ("iteration= ",i,"cost= ",res)
    print ("Validating output for OR GATE")
    result=sess.run(z,feed_dict={x:inp})
    print (result)

iteration=  0 cost=  0.803485
iteration=  1000 cost=  0.520551
iteration=  2000 cost=  0.378127
iteration=  3000 cost=  0.290027
iteration=  4000 cost=  0.233011
iteration=  5000 cost=  0.193718
iteration=  6000 cost=  0.165167
iteration=  7000 cost=  0.143558
iteration=  8000 cost=  0.126681
iteration=  9000 cost=  0.113167
iteration=  10000 cost=  0.102124
iteration=  11000 cost=  0.0929473
iteration=  12000 cost=  0.0852114
Validating output for OR GATE
[[ 0.17803274]
 [ 0.93139321]
 [ 0.93007511]
 [ 0.99880195]]


In [4]:
#NOT GATE 
import tensorflow as tf
import numpy as np
x=tf.placeholder(tf.float32,shape=[None,1])
y=tf.placeholder(tf.float32,shape=[None,1])

weights=tf.Variable(tf.random_normal([1,1]),dtype=tf.float32)
bias=tf.Variable(tf.random_normal([1]),dtype=tf.float32)



multiply1=tf.add(tf.matmul(x,weights),bias)
z=tf.nn.sigmoid(multiply1)


cost=tf.reduce_mean((y*tf.log(z)+(1-y)*tf.log(1-z))*-1)
optimizer = tf.train.GradientDescentOptimizer(0.01).minimize(cost)

inp=np.array([[1],[0]])
op=np.array([[0],[1]])
with tf.Session() as sess:
   
    tf.global_variables_initializer().run()
    for i in range(12001):
        res,_=sess.run([cost,optimizer],feed_dict={x:inp,y:op})
        if i%1000==0:
            print ("iteration= ",i,"cost= ",res)
    print ("Validating output for OR GATE")
    result=sess.run(z,feed_dict={x:inp})
    print (result)

iteration=  0 cost=  1.12037
iteration=  1000 cost=  0.396851
iteration=  2000 cost=  0.250212
iteration=  3000 cost=  0.178303
iteration=  4000 cost=  0.136763
iteration=  5000 cost=  0.110202
iteration=  6000 cost=  0.0919376
iteration=  7000 cost=  0.0786864
iteration=  8000 cost=  0.0686705
iteration=  9000 cost=  0.0608536
iteration=  10000 cost=  0.054594
iteration=  11000 cost=  0.049475
iteration=  12000 cost=  0.0452149
Validating output for OR GATE
[[ 0.03525008]
 [ 0.94692481]]


In [5]:
#NAND GATE 
import tensorflow as tf
import numpy as np
x=tf.placeholder(tf.float32,shape=[None,2])
y=tf.placeholder(tf.float32,shape=[None,1])

weights=tf.Variable(tf.random_normal([2,1]),dtype=tf.float32)
bias=tf.Variable(tf.random_normal([1]),dtype=tf.float32)



multiply1=tf.add(tf.matmul(x,weights),bias)
z=tf.nn.sigmoid(multiply1)


cost=tf.reduce_mean((y*tf.log(z)+(1-y)*tf.log(1-z))*-1)
optimizer = tf.train.GradientDescentOptimizer(0.01).minimize(cost)

inp=np.array([[0,0],[0,1],[1,0],[1,1]])
op=np.array([[1],[1],[1],[0]])
with tf.Session() as sess:
   
    tf.global_variables_initializer().run()
    for i in range(12001):
        res,_=sess.run([cost,optimizer],feed_dict={x:inp,y:op})
        if i%1000==0:
            print ("iteration= ",i,"cost= ",res)
    print ("Validating output for OR GATE")
    result=sess.run(z,feed_dict={x:inp})
    print (result)

iteration=  0 cost=  0.7882
iteration=  1000 cost=  0.505607
iteration=  2000 cost=  0.384714
iteration=  3000 cost=  0.314473
iteration=  4000 cost=  0.268033
iteration=  5000 cost=  0.234499
iteration=  6000 cost=  0.208834
iteration=  7000 cost=  0.1884
iteration=  8000 cost=  0.171665
iteration=  9000 cost=  0.157667
iteration=  10000 cost=  0.145764
iteration=  11000 cost=  0.135509
iteration=  12000 cost=  0.126575
Validating output for OR GATE
[[ 0.99434161]
 [ 0.86493772]
 [ 0.86628163]
 [ 0.19099525]]


In [6]:
#NOR GATE 
import tensorflow as tf
import numpy as np
x=tf.placeholder(tf.float32,shape=[None,2])
y=tf.placeholder(tf.float32,shape=[None,1])

weights=tf.Variable(tf.random_normal([2,1]),dtype=tf.float32)
bias=tf.Variable(tf.random_normal([1]),dtype=tf.float32)



multiply1=tf.add(tf.matmul(x,weights),bias)
z=tf.nn.sigmoid(multiply1)


cost=tf.reduce_mean((y*tf.log(z)+(1-y)*tf.log(1-z))*-1)
optimizer = tf.train.GradientDescentOptimizer(0.01).minimize(cost)

inp=np.array([[0,0],[0,1],[1,0],[1,1]])
op=np.array([[1],[0],[0],[0]])
with tf.Session() as sess:
   
    tf.global_variables_initializer().run()
    for i in range(12001):
        res,_=sess.run([cost,optimizer],feed_dict={x:inp,y:op})
        if i%1000==0:
            print ("iteration= ",i,"cost= ",res)
    print ("Validating output for OR GATE")
    result=sess.run(z,feed_dict={x:inp})
    print (result)

iteration=  0 cost=  1.24416
iteration=  1000 cost=  0.384885
iteration=  2000 cost=  0.290822
iteration=  3000 cost=  0.232227
iteration=  4000 cost=  0.192442
iteration=  5000 cost=  0.163841
iteration=  6000 cost=  0.142338
iteration=  7000 cost=  0.125607
iteration=  8000 cost=  0.112237
iteration=  9000 cost=  0.101322
iteration=  10000 cost=  0.0922542
iteration=  11000 cost=  0.0846098
iteration=  12000 cost=  0.0780849
Validating output for OR GATE
[[ 0.83602351]
 [ 0.06149696]
 [ 0.0665167 ]
 [ 0.00091497]]


In [7]:
#XOR GATE 
import tensorflow as tf
import numpy as np
x=tf.placeholder(tf.float32,shape=[None,2])
y=tf.placeholder(tf.float32,shape=[None,1])

weights=tf.Variable(tf.random_normal([2,1]),dtype=tf.float32)
bias=tf.Variable(tf.random_normal([1]),dtype=tf.float32)



multiply1=tf.add(tf.matmul(x,weights),bias)
z=tf.nn.sigmoid(multiply1)


cost=tf.reduce_mean((y*tf.log(z)+(1-y)*tf.log(1-z))*-1)
optimizer = tf.train.GradientDescentOptimizer(0.01).minimize(cost)

inp=np.array([[0,0],[0,1],[1,0],[1,1]])
op=np.array([[0],[1],[1],[0]])
with tf.Session() as sess:
   
    tf.global_variables_initializer().run()
    for i in range(12001):
        res,_=sess.run([cost,optimizer],feed_dict={x:inp,y:op})
        if i%1000==0:
            print ("iteration= ",i,"cost= ",res)
    print ("Validating output for OR GATE")
    result=sess.run(z,feed_dict={x:inp})
    print (result)

iteration=  0 cost=  0.838786
iteration=  1000 cost=  0.730763
iteration=  2000 cost=  0.710776
iteration=  3000 cost=  0.701288
iteration=  4000 cost=  0.696878
iteration=  5000 cost=  0.694852
iteration=  6000 cost=  0.693925
iteration=  7000 cost=  0.693502
iteration=  8000 cost=  0.693309
iteration=  9000 cost=  0.693221
iteration=  10000 cost=  0.693181
iteration=  11000 cost=  0.693163
iteration=  12000 cost=  0.693154
Validating output for OR GATE
[[ 0.50303411]
 [ 0.50051206]
 [ 0.50044018]
 [ 0.49791819]]


In [8]:
#XNOR GATE 
import tensorflow as tf
import numpy as np
x=tf.placeholder(tf.float32,shape=[None,2])
y=tf.placeholder(tf.float32,shape=[None,1])

weights=tf.Variable(tf.random_normal([2,1]),dtype=tf.float32)
bias=tf.Variable(tf.random_normal([1]),dtype=tf.float32)



multiply1=tf.add(tf.matmul(x,weights),bias)
z=tf.nn.sigmoid(multiply1)


cost=tf.reduce_mean((y*tf.log(z)+(1-y)*tf.log(1-z))*-1)
optimizer = tf.train.GradientDescentOptimizer(0.01).minimize(cost)

inp=np.array([[0,0],[0,1],[1,0],[1,1]])
op=np.array([[1],[0],[0],[1]])
with tf.Session() as sess:
   
    tf.global_variables_initializer().run()
    for i in range(12001):
        res,_=sess.run([cost,optimizer],feed_dict={x:inp,y:op})
        if i%1000==0:
            print ("iteration= ",i,"cost= ",res)
    print ("Validating output for OR GATE")
    result=sess.run(z,feed_dict={x:inp})
    print (result)

iteration=  0 cost=  0.742456
iteration=  1000 cost=  0.706341
iteration=  2000 cost=  0.697781
iteration=  3000 cost=  0.694852
iteration=  4000 cost=  0.693807
iteration=  5000 cost=  0.693414
iteration=  6000 cost=  0.693259
iteration=  7000 cost=  0.693196
iteration=  8000 cost=  0.693168
iteration=  9000 cost=  0.693157
iteration=  10000 cost=  0.693151
iteration=  11000 cost=  0.693149
iteration=  12000 cost=  0.693148
Validating output for OR GATE
[[ 0.5010643 ]
 [ 0.50026238]
 [ 0.50007164]
 [ 0.49926972]]
